Update azure-pipelines.yml for Azure Pipelines

diff --git a/pipelines/azure-pipelines.yml b/pipelines/azure-pipelines.yml
--- a/pipelines/azure-pipelines.yml
+++ b/pipelines/azure-pipelines.yml
@@ -43,11 +43,11 @@ steps:
     
     if [[ $downloadURL =~ $regex ]]
     then 
-       echo "Link valid"
+       echo ${downloadURL}
     else
-        echo "Link not valid"
+        echo "Download link could not be retrieved"
+        exit 1
     fi
-    echo ${downloadURL}
     
   displayName: 'Export Workflow'
 
