Update initialize_pipeline.yml for Azure Pipelines

diff --git a/pipelines/initialize_pipeline.yml b/pipelines/initialize_pipeline.yml
--- a/pipelines/initialize_pipeline.yml
+++ b/pipelines/initialize_pipeline.yml
@@ -116,6 +116,12 @@ steps:
           echo "##vso[task.complete result=Failed;]"
           exit 1
         fi
+                
+        if [ -z "$(type)" ]; then
+          echo "##vso[task.logissue type=error;]Missing parameter \"type\""
+          echo "##vso[task.complete result=Failed;]"
+          exit 1
+        fi
         
           rm -rf ./$(repoName)
 
